### ISSUE TITLE
Navigate function don't work

### ISSUE THREAD

**Issue by tranducduong1994** [electrode-io/ern-navigation#43] opened 2021-10-09 16:29 UTC
Hello,
For example: I have a MiniApp A

```
const appNavigator = new AppNavigator(
  {
    MiniAppA: App,
  },
  {
    initialScreen:'MiniAppA',
  },
);
appNavigator.registerAll('MiniAppA');
```
in MiniApp B, if I want to navigate to MiniApp A, i used navigate below:
```
this.navigate({
      path: 'MiniAppA',
    });
```
Issue:
If I use command: ern run-ios --miniapps shopping-product-miniapp --mainMiniAppName ShoppingListMiniapp to run code in the simulator, * navigate* function work well.
But When I use command: "ern create-container" to create a local container, then integrate it into a native app, * navigate* function didn't work.
This error was showed in xcode:
```
[javascript] 'Navigation Failed: ', { code: 'ENOHANDLER',
message: 'No registered request handler found' }
```
Thank you for help.

**Comment by deepueg** [comment] 2021-10-10 02:49
Duplicate of [#19](https://github.com/electrode-io/ernnavigation-api/issues/19)

**Comment by friederbluemle** [comment] 2021-11-29 23:52
See #19 for solution.

**Closed as completed by friederbluemle** 2021-11-29 23:52 UTC
